[[CcallMacros]]
git-tree-sha1 = "2f0f9f4b792a7443e3f3af760a7281e8923e9832"
repo-rev = "master"
repo-url = "https://github.com/ninjaaron/CcallMacros.jl"
uuid = "708bcaac-1406-11e9-0ec1-63a89b0112ed"
version = "0.1.0"
