# This file is machine-generated - editing it directly is not advised

<<<<<<< HEAD
[[CcallMacros]]
git-tree-sha1 = "4d39e89ccb4abf539dc5eeb79d2709fef843856b"
repo-rev = "master"
repo-url = "../CcallMacros.jl/"
uuid = "708bcaac-1406-11e9-0ec1-63a89b0112ed"
version = "0.1.3"
=======
>>>>>>> 728f93bad14bb37a93c80203aa6e822863d8399a
