name = "LibAaron"
uuid = "9c8a81ba-0db3-11e9-2404-49793f05cf58"
authors = ["Aaron Christianson <ninjaaron@gmail.com>"]
version = "0.1.1"

[deps]
Revise = "295af30f-e4ad-537b-8983-00126c2a3abe"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
